name: Pull Request

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      - name: go vendor
        run: go mod vendor
      - name: go test
        run: go test ./...